[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
backmysol_contract = "CjjskajkSeYgfQxx88wcaLvPSe3RmGgbpzkHpnQevyB6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize = "npx ts-node scripts/initialize.ts"
