[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
backmysol_contract = "CjjskajkSeYgfQxx88wcaLvPSe3RmGgbpzkHpnQevyB6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=2ac63520-9273-4f29-8ab6-bada9f72124a"
wallet = "/Users/maigia/.config/solana/mainnet-deployer.json"
#cluster = "devnet" # <--- Đổi thành devnet
#wallet = "~/.config/solana/id.json" # Đảm bảo đường dẫn đúng tới ví của bạn

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize = "npx ts-node scripts/initialize.ts"
